config/routes.rb
Rails.application.routes.draw do
      devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  resources :story

  resources :between do 
    resources :comments
  end

  root 'calendar#index'
  

end

app/models/between.rb
class Between < ActiveRecord::Base
	mount_uploader :photo, PhotoUploader
	has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :between
end

app/models/story.rb
class Story < ActiveRecord::Base
	mount_uploader :photo, PhotoUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/between_controller.rb
class BetweenController < ApplicationController
	before_action :authenticate_user!
	def new
	end

	def create
		@between = Between.new(between_params)
		
		@between.save
		redirect_to @between
	end

	def show
		@between = Between.find(params[:id])
	end

	def index
		@between = Between.all
	end

private
	def between_params
		params.require(:between).permit(:title, :text, :photo)
	end

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
 before_action :authenticate_user!
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@between = Between.find(params[:between_id])
		@comment = @between.comments.new(comment_params)
		@comment.commenter = current_user.email
		@comment.save
		redirect_to between_path(@between)
	end

	private
		def comment_params
			params.require(:comment).permit(:body)
		end
end

app/controllers/story_controller.rb
class StoryController < ApplicationController
	before_action :authenticate_user!

	def new
	end

	def create
		@story = Story.new(story_params)
		
		@story.save
		redirect_to @story
	end

	def show
		@story = Story.find(params[:id])
	end

	def index
		@story = Story.all
	end

	private 
		def story_params
			params.require(:story).permit(:title, :text, :photo)
		end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :configure_sign_up_params, only: [:create]
 before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/between_helper.rb
module BetweenHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/story_helper.rb
module StoryHelper
end

app/views/between/_form.html.erb
<div class="between">
	<p>
		<%= image_tag @between.photo, :width => 400 %>
	</p>
	<p>
		<strong>Title:</strong>
		<%= @between.title %>
	</p>
	<p>
		<strong>Text:</strong>
		<%= @between.text %>
	</p>
</div>

<div class="comment">
<h4>Comments</h4>
<% @between.comments.each do |comment| %>
	<p>
		<strong><%= comment.commenter %>:</strong>
		<%= comment.body %>
	</p>
<% end %>

<br><h4>Add a comment:</h4>
<%= form_for([@between, @between.comments.build]) do |f| %>
	
	<p>	
		<%= f.label :comment %><br>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
<%= link_to 'Back', between_index_path %>
</div>

app/views/between/new.html.erb
<div class="between">
<h1><span style="background-color:#FFE3EE">Between diary</span></h1>
<%= form_for :between, url: between_index_path do |f| %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
    	<%= f.label :photo %><br>
    	<center><%= f.file_field :photo %></center>
  	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>
</div>

app/views/between/show.html.erb
<%= render 'form' %>

app/views/calendar/index.html.erb
<div class="container">
	<div class = "log_in">
		<% if user_signed_in? %>
		  <p><%= current_user.email %></p>
		  <p><%= image_tag(current_user.avatar, :width => 200) %></p>
		  <p><%= link_to "로그아웃", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></p>
		<% else %>
		  <p><%= link_to "로그인", new_user_session_path %></p>
		<% end %>
	</div>

	<%= month_calendar do |between_date| %>
	  <% date_output = between_date.strftime("%d") %>
	  <%= date_output %>
	  <% between_btn = Between.where(:created_at => (between_date.to_date.beginning_of_day..between_date.to_date.end_of_day)).first %>
      <% if between_btn %>
        <br><%= link_to 'Between', between_path(between_btn), class: 'btn btn-default' %>
      <% end %>
    <% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
  .jumbotron {text-align:center;
  	height:300px;
  	font-family: 'Lobster', cursive;
  	font-weight:lighter;}
  .log_in {text-align:center;
  	font-family: 'Jeju Gothic', serif;
  }
  .story {text-align:center;
  	font-family: 'Jeju Gothic', serif;}
  .between {text-align:center;
  	font-family: 'Jeju Gothic', serif;}
 
  
  table{width:100;
  	margin:auto;
  	text-align:left;
    top:50px;}
  textarea{width:500px;height:200px;}
  
  body {
    margin: 0 auto;
    max-width: 80em;
  }

  </style>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "My diary", story_index_path %></li>
      <li><%= link_to "Between diary", between_index_path %></li>  
    </ul>

      
  </div>
</nav>

<div class="jumbotron">
  <h1 class="belong_to_you">Belong to You</h1>
</div>
 
<%= yield %>

</body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>

            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= start_date.strftime("%U").to_i %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/story/index.html.erb
<div class="story">
<h1><span style="background-color:#D2FFD2">My diary</span></h1>
 
<table>
  <tr>
    <th class="col-xs-3">Title</th>
    <th class="col-xs-6">Text</th>
  </tr>
 
  <% @story.each do |story| %>
    <tr>
      <td class="col-xs-3"><%= story.title %></td>
      <td class="col-xs-6"><%= story.text %></td>
      <td><%= link_to 'Show', story_path(story) %></td>
    </tr>
  <% end %>
</table>

<br><button><%= link_to 'New diary', new_story_path %></button>
</div>

app/views/story/new.html.erb
<div class="story">
<h1><span style="background-color:#D2FFD2">Today's story</span></h1>

<%= form_for :story, url: story_index_path do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
 <p>
    <%= f.label :photo %><br>
    <center><%= f.file_field :photo %></center>
  </p> 
  
  <p>
    <br><%= f.submit %>
  </p>
<% end %>
</div>

app/views/story/show.html.erb
<div class="story">
<p>
	<%= image_tag @story.photo,:width => 400  %>
</p>

<p>
	<strong>Title:</strong>
	<%= @story.title %>
</p>

<p>
	<strong>Text:</strong>
	<%= @story.text %>
</p>

<%= link_to 'Back', story_index_path %>
</div>